version: '3.8'

services:
  app:
    image: user-service:latest
    container_name: user-application
    ports:
      - "4321:4321"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
